# render.yaml
services:
  - type: web
    name: knowledge-graph
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --timeout 120
    plan: free
